#%RAML 0.8

title: Web Series API
baseUri: http://webseries.herokuapp.com/api
version: v1

securitySchemes:
  - basic:
      description: |
              This API supports Basic Authentication.

      type: Basic Authentication
  - oauth_v2:
      description: |
          This Connection uses oauth_v2

      type: OAuth 2.0
      settings:
          authorizationUri: https://api.tviso.com/auth_token
          accessTokenUri: https://api.series.ly/v2/user/user_login

traits:
  - paged:
      queryParameters:
        page:
          description: The number of the page to get
          type: number
  - auth:
      queryParameters:
        auth_token:
          description: Authorization token
          type: string
      headers:
        Authorization:
          description: Basic authentication header
          example: |
            Authorization: Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ==
      responses:
        401:
          body:
            text/plain:
              schema: |
                Autorización incorrecta

/usuario:
  post:
    description: |
      Registers a new user

    body:
      application/json:
        schema: |
          {
            "nickname"  : "Pepe",
            "password" : "pepe"
          }

    responses:
      201:

  /login:
    post:
      description: |
        Returns the user encoded in base64 and the token if the user exists

      body:
        application/json:
          schema: |
            {
              "user" : "Pepe",
              "password" : "pepe"
            }

      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "basic": "UGVwZTpwZXBl",
                  "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpbiI6IlBlcGUiLCJleHAiOjE0NDgwNjE5NjkyOTl9.rO0tuIZM7-4JrAauXOi3uYa_VXXkcgmLTJ0EzoiTqFk"
                }
        401:
          body:
            text/plain:
              schema: |
                Usuario o password incorrectos
  /{usuario_id}:
    get:
      description: |
        Returns the user encoded in base64 and the token if the user exists

      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "id": 1,
                  "nickname": "Pepe",
                  "password": "pepe",
                  "token": null,
                  "createdAt": "2015-11-13T22:10:27.696Z",
                  "updatedAt": "2015-11-13T22:10:27.696Z"
                }
        400:
          body:
            text/plain:
              schema: |
                Error: El id no es un número
        404:
    put:
      description: |
        Updates the user information

      is: [auth]
      securedBy: [basic]

      body:
        application/json:
          example: |
            {
              "password" : "newPassword"
            }
      responses:
        204:
        400:
          body:
            text/plain:
              schema: |
                Error: El id no es un número
        404:
    delete:
      description: |
        Deletes the user

      is: [auth]
      securedBy: [basic]
      responses:
        204:
        400:
          body:
            text/plain:
              schema: |
                Error: El id no es un número
        404:
    /series:
      get:
        description: |
          Get the series from the user

        responses:
          200:
            body:
              application/json:
                example: |
                  [
                    {
                      "id": 1,
                      "title": "The Big Bang Theory",
                      "description": "descripción de la serie The Big Bang Theory",
                      "createdAt": "2015-11-13T23:15:36.364Z",
                      "updatedAt": "2015-11-13T23:15:36.364Z",
                      "UsuarioId": 1
                    },
                    {
                      "id": 2,
                      "title": "Breaking Bad",
                      "description": "descripción de la serie Breaking Bad",
                      "createdAt": "2015-11-13T23:15:36.393Z",
                      "updatedAt": "2015-11-13T23:15:36.393Z",
                      "UsuarioId": 1
                    }
                  ]
          400:
            body:
              text/plain:
                schema: |
                  Error: El id no es un número
          404:

/series:
  get:
    is: [paged]
    description: |
      Returns all the series

    responses:
      200:
        body:
          application/json:
            schema: |
              {
                "series": [
                  {
                    "id": 1,
                    "title": "The Big Bang Theory",
                    "description": "descripción de la serie The Big Bang Theory",
                    "createdAt": "2015-11-15T20:18:00.373Z",
                    "updatedAt": "2015-11-15T20:18:00.373Z",
                    "UsuarioId": 1
                  },
                  {
                    "id": 2,
                    "title": "Breaking Bad",
                    "description": "descripción de la serie Breaking Bad",
                    "createdAt": "2015-11-15T20:18:00.396Z",
                    "updatedAt": "2015-11-15T20:18:00.396Z",
                    "UsuarioId": 1
                  }
                ],
                "_links": {
                  "self": "/api/series",
                  "first": "/api/series/?page=1",
                  "last": "/api/series/?page=1"
                }
              }
  post:
    is: [auth]
    securedBy: [basic]
    description: |
      Creates a new serie

    body:
      application/json:
        schema: |
          {
            "title" : "Serie title",
            "description" : "Serie description"
          }

    responses:
      201:
        body:
          text/plain:
            schema: |
              Serie creada correctamente
  /{serie_id}:
    put:
      description: |
        Updates the serie information

      is: [auth]
      securedBy: [basic]
      body:
        application/json:
          schema: |
            {
              "title" : "Serie title",
              "description" : "Serie description"
            }

      responses:
        204:
        404:
          body:
            text/plain:
              schema: |
                La serie no existe
        400:
          body:
            text/plain:
              schema: |
                Error: El id no es un número
    delete:
      description: |
        Detetes the serie

      is: [auth]
      securedBy: [basic]
      responses:
        204:
        404:
          body:
            text/plain:
              schema: |
                La serie no existe
        400:
          body:
            text/plain:
              schema: |
                Error: El id no es un número
    get:
      description: |
        Gets the serie information and its seasons and comments

      is: [paged]
      responses:
        200:
          body:
            application/json:
              schema: |
                {
                  "serie": {
                    "id": 1,
                    "title": "The Big Bang Theory",
                    "description": "descripción de la serie The Big Bang Theory",
                    "createdAt": "2015-11-15T20:18:00.373Z",
                    "updatedAt": "2015-11-15T20:18:00.373Z",
                    "UsuarioId": 1,
                    "temporadas": [
                      {
                        "id": 1,
                        "season": 1
                      }


                    ],
                    "comentarios": [
                      {
                        "id": 61,
                        "comment": "Comentario a serie 1",
                        "createdAt": "2015-11-15T20:18:00.434Z",
                        "UsuarioId": 1
                      }


                    ]
                  },
                  "_links": {
                    "self": "/api/series/1",
                    "first": "/api/series/1?page=1",
                    "last": "/api/series/1?page=2",
                    "next": "/api/series/1?page=2"
                  }
                }
        404:
          body:
            text/plain:
              schema: |
                La serie no existe
        400:
          body:
            text/plain:
              schema: |
                Error: El id no es un número
    /comentario:
      post:
        description: |
          Adds a new comment to the serie

        is: [auth]
        securedBy: [basic]
        body:
          application/json:
            schema: |
              {
                "comment" : "New comment"
              }
        responses:
          201:
            body:
              text/plain:
                schema: |
                  Comentario creado correctamente
          404:
            body:
              text/plain:
                schema: |
                  La serie no existe
          400:
            body:
              text/plain:
                schema: |
                  Error: El id no es un número
      /{comment_id}:
        put:
          description: |
            Updates the comment

          is: [auth]
          securedBy: [basic]
          body:
            application/json:
              schema: |
                {
                  "comment" : "Comment edited"
                }
          responses:
            204:
            404:
              body:
                text/plain:
                  example: |
                    La serie no existe
            400:
              body:
                text/plain:
                  example: |
                    Error: El id del comentario no es un número
        delete:
          description: |
            Deletes the comment

          is: [auth]
          securedBy: [basic]
          responses:
            204:
            404:
              body:
                text/plain:
                  example: |
                    La serie no existe
            400:
              body:
                text/plain:
                  example: |
                    Error: El id del comentario no es un número
    /temporada:
      post:
        description: |
          Adds a new season to a serie.

        is: [auth]
        securedBy: [basic]
        responses:
          201:
            body:
              text/plain:
                schema: |
                  Temporada creada correctamente
          404:
            body:
              text/plain:
                schema: |
                  La serie no existe
          400:
            body:
              text/plain:
                schema: |
                  Error: El id no es un número
      /{season_id}:
        get:
          description: |
            Gets all the episodes of a season

          responses:
            200:
              body:
                application/json:
                  schema: |
                    [
                      {
                        "id": 1,
                        "title": "Capitulo 1",
                        "createdAt": "2015-11-15T20:18:00.386Z",
                        "updatedAt": "2015-11-15T20:18:00.386Z",
                        "TemporadaId": 1
                      },

                      ...
                    ]
            404:
              body:
                text/plain:
                  example: |
                    La temporada no existe
            400:
              body:
                text/plain:
                  example: |
                    Error: El id de la temporada no es un número
        delete:
          description: |
            Deletes the season

          is: [auth]
          securedBy: [basic]
          responses:
            204:
            404:
              body:
                text/plain:
                  example: |
                    La temporada no existe
            400:
              body:
                text/plain:
                  example: |
                    Error: El id de la temporada no es un número
        /capitulo:
          post:
            description: |
              Adds a new episode to a season

            is: [auth]
            securedBy: [basic]
            body:
              application/json:
                schema: |
                  {
                    "title" : "Episode title"
                  }
            responses:
              201:
              404:
                body:
                  text/plain:
                    example: |
                      La temporada no existe
              400:
                body:
                  text/plain:
                    example: |
                      Error: El id de la temporada no es un número
          /{episode_id}:
            get:
              description: |
                Gets the list of comments of an episode

              is: [paged]
              securedBy: [basic]
              responses:
                200:
                  body:
                    application/json:
                      schema: |
                        {
                          "comentarios": [
                            {
                              "id": 1,
                              "comment": "Comentario 1",
                              "createdAt": "2015-11-15T20:18:00.421Z",
                              "updatedAt": "2015-11-15T20:18:00.421Z",
                              "UsuarioId": 1
                            }


                          ],
                          "_links": {
                            "self": "/api/series/1/temporada/1/capitulo/1",
                            "first": "/api/series/1/temporada/1/capitulo/1?page=1",
                            "last": "/api/series/1/temporada/1/capitulo/1?page=1"
                          }
                        }
                404:
                  body:
                    text/plain:
                      example: |
                        El capítulo no existe
                400:
                  body:
                    text/plain:
                      example: |
                        Error: El id del capítulo no es un número
            put:
              description: |
                Updates the information of an episode

              is: [auth]
              securedBy: [basic]
              body:
                application/json:
                  schema: |
                    {
                      "title" : "Episode title edited"
                    }
              responses:
                204:
                404:
                  body:
                    text/plain:
                      example: |
                        El capítulo no existe
                400:
                  body:
                    text/plain:
                      example: |
                        Error: El id del capítulo no es un número
            delete:
              description: |
                Deletes the episode

              is: [auth]
              securedBy: [basic]
              responses:
                204:
                404:
                  body:
                    text/plain:
                      example: |
                        El capítulo no existe
                400:
                  body:
                    text/plain:
                      example: |
                        Error: El id del capítulo no es un número
            /comentario:
              post:
                description: |
                  Creates a new comment of an episode

                is: [auth]
                securedBy: [basic]
                body:
                  application/json:
                    schema: |
                      {
                        "comment" : "New comment"
                      }
                responses:
                  201:
                  404:
                    body:
                      text/plain:
                        example: |
                          El capítulo no existe
                  400:
                    body:
                      text/plain:
                        example: |
                          Error: El id del capítulo no es un número
              /{comment_id}:
                put:
                  description: |
                    Updates the comment

                  is: [auth]
                  securedBy: [basic]
                  body:
                    application/json:
                      schema: |
                        {
                          "comment" : "Comment edited"
                        }
                  responses:
                    204:
                    404:
                      body:
                        text/plain:
                          example: |
                            El comentario no existe
                    400:
                      body:
                        text/plain:
                          example: |
                            Error: El id del comentario no es un número
                delete:
                  description: |
                    Deletes the comment

                  is: [auth]
                  securedBy: [basic]
                  responses:
                    204:
                    404:
                      body:
                        text/plain:
                          example: |
                            El comentario no existe
                    400:
                      body:
                        text/plain:
                          example: |
                            Error: El id del comentario no es un número

/tviso:
  /noticias:
    /interesantes:
      securedBy: [oauth_v2]
      get:
        description: |
          Gets the promoted news

        responses:
          200:
            body:
              application/json:
                schema: |
                  {
                    "results":[
                      {
                        "idn":"56444872a53590c7158b4567",
                        "title":"Nuevo trailer de 'The Finest Hours'",
                        "short_text":"Short text",
                        "idm":1572204,
                        "mediaType":2,
                        "status":"like",
                        "comments":0,
                        "created":"2015-11-12T09:06:10+01:00",
                        "tags":["the ","finest","hours"],
                        "author":{
                          "uid":3326553,
                          "nick":"greml",
                          "full_name":"Carles Marti Casquero",
                          "img_user":"https:\/\/cdn.tviso.com\/scripts\/usr_img.php?id=B7931D8C93E4DA4E5445"
                          },
                        "image":{"notice":"\/d0\/b3\/d0b3b62c46a80e12212188c67e9be5a5.jpg","country":"XX"},
                        "total_votes":0,
                        "views":496,
                        "source":"",
                        "working":1,
                        "section":2,
                        "promoted":true,
                        "video":{"code":"7vNKR34MX0k","host":16},
                        "text":"the complete news"
                      }


                    ],
                    "error":0
                  }

    /promocionadas:
      get:
        description: |
          Gets the promoted news

        responses:
          200:
            body:
              application/json:
                schema: |
                  {
                    "results":[
                      {
                        "idn":"56444872a53590c7158b4567",
                        "title":"Nuevo trailer de 'The Finest Hours'",
                        "short_text":"Short text",
                        "idm":1572204,
                        "mediaType":2,
                        "status":"like",
                        "comments":0,
                        "created":"2015-11-12T09:06:10+01:00",
                        "tags":["the ","finest","hours"],
                        "author":{
                          "uid":3326553,
                          "nick":"greml",
                          "full_name":"Carles Marti Casquero",
                          "img_user":"https:\/\/cdn.tviso.com\/scripts\/usr_img.php?id=B7931D8C93E4DA4E5445"
                          },
                        "image":{"notice":"\/d0\/b3\/d0b3b62c46a80e12212188c67e9be5a5.jpg","country":"XX"},
                        "total_votes":0,
                        "views":496,
                        "source":"",
                        "working":1,
                        "section":2,
                        "promoted":true,
                        "video":{"code":"7vNKR34MX0k","host":16},
                        "text":"the complete news"
                      }


                    ],
                    "error":0
                  }

    /mas_vistas:
      get:
        description: |
          Gets the most seen news

        responses:
          200:
            body:
              application/json:
                schema: |
                  {
                    "results":[
                      {
                        "idn":"56444872a53590c7158b4567",
                        "title":"Nuevo trailer de 'The Finest Hours'",
                        "short_text":"Short text",
                        "idm":1572204,
                        "mediaType":2,
                        "status":"like",
                        "comments":0,
                        "created":"2015-11-12T09:06:10+01:00",
                        "tags":["the ","finest","hours"],
                        "author":{
                          "uid":3326553,
                          "nick":"greml",
                          "full_name":"Carles Marti Casquero",
                          "img_user":"https:\/\/cdn.tviso.com\/scripts\/usr_img.php?id=B7931D8C93E4DA4E5445"
                          },
                        "image":{"notice":"\/d0\/b3\/d0b3b62c46a80e12212188c67e9be5a5.jpg","country":"XX"},
                        "total_votes":0,
                        "views":496,
                        "source":"",
                        "working":1,
                        "section":2,
                        "promoted":true,
                        "video":{"code":"7vNKR34MX0k","host":16},
                        "text":"the complete news"
                      }


                    ],
                    "error":0
                  }

    /mas_votadas:
      get:
        description: |
          Gets the most voted news

        responses:
          200:
            body:
              application/json:
                schema: |
                  {
                    "results":[
                      {
                        "idn":"56444872a53590c7158b4567",
                        "title":"Nuevo trailer de 'The Finest Hours'",
                        "short_text":"Short text",
                        "idm":1572204,
                        "mediaType":2,
                        "status":"like",
                        "comments":0,
                        "created":"2015-11-12T09:06:10+01:00",
                        "tags":["the ","finest","hours"],
                        "author":{
                          "uid":3326553,
                          "nick":"greml",
                          "full_name":"Carles Marti Casquero",
                          "img_user":"https:\/\/cdn.tviso.com\/scripts\/usr_img.php?id=B7931D8C93E4DA4E5445"
                          },
                        "image":{"notice":"\/d0\/b3\/d0b3b62c46a80e12212188c67e9be5a5.jpg","country":"XX"},
                        "total_votes":0,
                        "views":496,
                        "source":"",
                        "working":1,
                        "section":2,
                        "promoted":true,
                        "video":{"code":"7vNKR34MX0k","host":16},
                        "text":"the complete news"
                      }


                    ],
                    "error":0
                  }

    /top:
      get:
        description: |
          Gets the top news

        responses:
          200:
            body:
              application/json:
                schema: |
                  {
                    "results":[
                      {
                        "idn":"56444872a53590c7158b4567",
                        "title":"Nuevo trailer de 'The Finest Hours'",
                        "short_text":"Short text",
                        "idm":1572204,
                        "mediaType":2,
                        "status":"like",
                        "comments":0,
                        "created":"2015-11-12T09:06:10+01:00",
                        "tags":["the ","finest","hours"],
                        "author":{
                          "uid":3326553,
                          "nick":"greml",
                          "full_name":"Carles Marti Casquero",
                          "img_user":"https:\/\/cdn.tviso.com\/scripts\/usr_img.php?id=B7931D8C93E4DA4E5445"
                          },
                        "image":{"notice":"\/d0\/b3\/d0b3b62c46a80e12212188c67e9be5a5.jpg","country":"XX"},
                        "total_votes":0,
                        "views":496,
                        "source":"",
                        "working":1,
                        "section":2,
                        "promoted":true,
                        "video":{"code":"7vNKR34MX0k","host":16},
                        "text":"the complete news"
                      }


                    ],
                    "error":0
                  }

    /ultimas:
      get:
        description: |
          Gets the last news

        responses:
          200:
            body:
              application/json:
                schema: |
                  {
                    "results":[
                      {
                        "idn":"56444872a53590c7158b4567",
                        "title":"Nuevo trailer de 'The Finest Hours'",
                        "short_text":"Short text",
                        "idm":1572204,
                        "mediaType":2,
                        "status":"like",
                        "comments":0,
                        "created":"2015-11-12T09:06:10+01:00",
                        "tags":["the ","finest","hours"],
                        "author":{
                          "uid":3326553,
                          "nick":"greml",
                          "full_name":"Carles Marti Casquero",
                          "img_user":"https:\/\/cdn.tviso.com\/scripts\/usr_img.php?id=B7931D8C93E4DA4E5445"
                          },
                        "image":{"notice":"\/d0\/b3\/d0b3b62c46a80e12212188c67e9be5a5.jpg","country":"XX"},
                        "total_votes":0,
                        "views":496,
                        "source":"",
                        "working":1,
                        "section":2,
                        "promoted":true,
                        "video":{"code":"7vNKR34MX0k","host":16},
                        "text":"the complete news"
                      }


                    ],
                    "error":0
                  }

    /{noticia_id}:
      get:
        description: |
          Gets the full news

        responses:
          200:
            body:
              application/json:
                schema: |
                  {
                    "results": [
                        {
                            "idn": "51763cbf892b2bea6700002d",
                            "title": "Nuevas imágenes de 'The Amazing Spider-Man 2' con Jamie Foxx y Dane DeHaan",
                            "short_text": "El director Marc Webb vuelve a la carga en su cuenta de Twitter, ofreciendo a sus fans nuevas fotografías de 'The Amazing Spider-Man 2'. El cineasta es un asiduo a usar su perfil de la red social para...",
                            "idm": 19339,
                            "mediaType": 2,
                            "status": 1,
                            "comments": 0,
                            "created": "2013-04-23T09:48:15+02:00",
                            "tags": [
                                "amazing",
                                "spiderman",
                                "jamie foxx",
                                "dane dehaan"
                            ],
                            "author": {
                                "uid": 297374,
                                "nick": "JaviChaques",
                                "full_name": "Javi Chaqués",
                                "img_user": "https://cdn.tviso.com/scripts/usr_img.php?id=TFF44K4E6E"
                            },
                            "image": "https://cdn.tviso.com/noticia/777C7NFKNNRDV75D4EC6.jpg",
                            "total_votes": 0,
                            "shared": 0,
                            "views": 171,
                            "source": "http://www.ecartelera.com/noticias/13563/"
                        }


                   ],
                   "error":0
                  }

  /visualizaciones:
    get:
      description: |
        Gets the visualization data of a serie

      responses:
        200:
          body:
            application/json:
              schema: |
                {
                  "data": [
                    {
                        "date": "2013-05-11T00:00:00+02:00",
                        "views": 352
                    },
                    {
                        "date": "2013-05-12T00:00:00+02:00",
                        "views": 415
                    },
                    {
                        "date": "2013-05-13T00:00:00+02:00",
                        "views": 387
                    },
                    {
                        "date": "2013-05-14T00:00:00+02:00",
                        "views": 347
                    }
                  ],
                  "error": 0
                }
      queryParameters:
        title:
          description: |
            Title of the serie to get the data
